Repository google/santa, pull requests merged in 2018-05, with the labels that each got.

#257 fileinfo: whitelist bundle extensions when performing an ancestor search
  Santa.xcodeproj/project.pbxproj
  Source/common/SNTFileInfo.m
  Tests/LogicTests/Resources/DirectoryBundle/Contents/Info.plist
  Tests/LogicTests/Resources/DirectoryBundle/Contents/MacOS/DirectoryBundle
  Tests/LogicTests/Resources/DirectoryBundle/Contents/Resources/BundleExample.app/Contents/Info.plist
  Tests/LogicTests/Resources/DirectoryBundle/Contents/Resources/BundleExample.app/Contents/MacOS/BundleExample
  Tests/LogicTests/SNTFileInfoTest.m
Labels: bug

#258 Project: Use MOLXPCConnection
  Podfile
  Podfile.lock
  Santa.xcodeproj/project.pbxproj
  Source/SantaGUI/SNTAppDelegate.m
  Source/SantaGUI/SNTNotificationManager.m
  Source/common/SNTXPCConnection.h
  Source/common/SNTXPCConnection.m
  Source/common/SNTXPCControlInterface.h
  Source/common/SNTXPCControlInterface.m
  Source/santabs/SNTBundleService.m
  Source/santabs/main.m
  Source/santactl/Commands/SNTCommandBundleInfo.m
  Source/santactl/Commands/SNTCommandCheckCache.m
  Source/santactl/Commands/SNTCommandFileInfo.m
  Source/santactl/Commands/SNTCommandFlushCache.m
  Source/santactl/Commands/SNTCommandRule.m
  Source/santactl/Commands/SNTCommandStatus.m
  Source/santactl/Commands/SNTCommandVersion.m
  Source/santactl/Commands/sync/SNTCommandSync.m
  Source/santactl/Commands/sync/SNTCommandSyncEventUpload.m
  Source/santactl/Commands/sync/SNTCommandSyncManager.h
  Source/santactl/Commands/sync/SNTCommandSyncManager.m
  Source/santactl/Commands/sync/SNTCommandSyncPostflight.m
  Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
  Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.m
  Source/santactl/Commands/sync/SNTCommandSyncStage.h
  Source/santactl/Commands/sync/SNTCommandSyncStage.m
  Source/santactl/Commands/sync/SNTCommandSyncState.h
  Source/santactl/SNTCommand.h
  Source/santactl/SNTCommand.m
  Source/santactl/SNTCommandController.h
  Source/santactl/SNTCommandController.m
  Source/santad/Logs/SNTEventLog.h
  Source/santad/SNTApplication.m
  Source/santad/SNTDaemonControlController.m
  Source/santad/SNTNotificationQueue.h
  Source/santad/SNTNotificationQueue.m
  Source/santad/SNTSyncdQueue.h
  Source/santad/SNTSyncdQueue.m
  Tests/LogicTests/SNTCommandFileInfoTest.m
  Tests/LogicTests/SNTCommandSyncTest.m
  Tests/LogicTests/SNTXPCConnectionTest.m
Labels: cleanup

#264 Update project for Xcode 9.1, add codesigning flags
  Santa.xcodeproj/project.pbxproj
  Santa.xcodeproj/xcshareddata/xcschemes/All.xcscheme
  Santa.xcodeproj/xcshareddata/xcschemes/KernelTests.xcscheme
  Santa.xcodeproj/xcshareddata/xcschemes/LogicTests.xcscheme
  Santa.xcodeproj/xcshareddata/xcschemes/Santa.xcscheme
  Santa.xcodeproj/xcshareddata/xcschemes/santa-driver.xcscheme
  Santa.xcodeproj/xcshareddata/xcschemes/santabs.xcscheme
  Santa.xcodeproj/xcshareddata/xcschemes/santactl.xcscheme
  Santa.xcodeproj/xcshareddata/xcschemes/santad.xcscheme
  Source/SantaGUI/Resources/MessageWindow.xib
  Source/common/SNTRule.m
  Source/common/SNTStoredEvent.m
  Source/common/SNTXPCControlInterface.h
  Source/santactl/Commands/sync/SNTCommandSyncEventUpload.m
  Source/santactl/Commands/sync/SNTCommandSyncManager.m
  Source/santactl/Commands/sync/SNTCommandSyncPostflight.m
  Source/santad/DataLayer/SNTRuleTable.m
  Source/santad/Logs/SNTEventLog.m
  Source/santad/SNTDaemonControlController.m
  Source/santad/SNTSyncdQueue.h
  Source/santad/SNTSyncdQueue.m
Labels: cleanup

#256 Optional MachineID for Logs
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/santad/Logs/SNTEventLog.h
  Source/santad/Logs/SNTEventLog.m
  Source/santad/Logs/SNTSyslogEventLog.m
Labels: cla:no

#271 SantaCache: Templatize key types
  Source/santa-driver/SantaCache.h
  Source/santa-driver/SantaDecisionManager.cc
  Source/santa-driver/SantaDecisionManager.h
  Tests/LogicTests/SantaCacheTest.mm
Labels: enhancement
