Repository google/santa, pull requests merged in 2018-06, with the labels that each got.

#272 santa-driver: Fix cache CAS operations, which haven't been working
  Source/santa-driver/SantaCache.h
  Source/santa-driver/SantaDecisionManager.cc
  Source/santa-driver/SantaDecisionManager.h
Labels: bug, enhancement

#274 Project: Update cocoapods, again
  Podfile.lock
  Santa.xcodeproj/project.pbxproj
Labels: cleanup

#273 SantaCache: Add very basic distribution test
  Source/santa-driver/SantaCache.h
  Tests/LogicTests/SantaCacheTest.mm
Labels: enhancement

#275 SantaCache: Add command to print histogram of bucket distribution
  Santa.xcodeproj/project.pbxproj
  Source/common/SNTKernelCommon.h
  Source/common/SNTXPCControlInterface.h
  Source/santa-driver/SantaDecisionManager.cc
  Source/santa-driver/SantaDecisionManager.h
  Source/santa-driver/SantaDriverClient.cc
  Source/santa-driver/SantaDriverClient.h
  Source/santactl/Commands/SNTCommandBundleInfo.m
  Source/santactl/Commands/SNTCommandCacheHistogram.m
  Source/santactl/Commands/SNTCommandCheckCache.m
  Source/santactl/Commands/SNTCommandFlushCache.m
  Source/santad/SNTDaemonControlController.m
  Source/santad/SNTDriverManager.h
  Source/santad/SNTDriverManager.m
Labels: enhancement

#277 santad: Don't get code signature info for non Mach-O's.
  Source/santad/SNTExecutionController.m
Labels: enhancement

#276 santa-driver: Switch to a struct for vnode IDs, holding both the file…
  Santa.xcodeproj/project.pbxproj
  Source/common/SNTKernelCommon.h
  Source/common/SNTXPCControlInterface.h
  Source/santa-driver/SantaCache.h
  Source/santa-driver/SantaDecisionManager.cc
  Source/santa-driver/SantaDecisionManager.h
  Source/santa-driver/SantaDriverClient.cc
  Source/santactl/Commands/SNTCommandCheckCache.m
  Source/santactl/Commands/SNTCommandStatus.m
  Source/santad/Logs/SNTEventLog.m
  Source/santad/SNTApplication.m
  Source/santad/SNTCachedDecision.h
  Source/santad/SNTDaemonControlController.m
  Source/santad/SNTDriverManager.h
  Source/santad/SNTDriverManager.m
  Source/santad/SNTExecutionController.m
  Tests/KernelTests/main.mm
  Tests/LogicTests/SNTExecutionControllerTest.m
Labels: enhancement

#280 santa-driver: Stop checking hasdirtyblks, the loader handles this
  Source/santa-driver/SantaDecisionManager.cc
Labels: cleanup

#281 santa-driver: Re-factor some destruction methods
  Source/santa-driver/SantaDecisionManager.cc
  Source/santa-driver/SantaDriverClient.cc
  Source/santa-driver/SantaDriverClient.h
Labels: bug, cleanup

#282 KernelTests: Simplify kernel tests
  Rakefile
  Santa.xcodeproj/xcshareddata/xcschemes/KernelTests.xcscheme
  Source/santa-driver/SantaDriverClient.cc
  Source/santa-driver/SantaDriverClient.h
  Tests/KernelTests/main.mm
Labels: enhancement

#278 santad: Wait for driver appearance using IOKit notifications.
  Conf/com.google.santad.plist
  Source/common/SNTXPCControlInterface.h
  Source/santa-driver/SantaDecisionManager.cc
  Source/santa-driver/SantaDecisionManager.h
  Source/santa-driver/SantaDriverClient.cc
  Source/santactl/Commands/SNTCommandStatus.m
  Source/santad/SNTDaemonControlController.m
  Source/santad/SNTDriverManager.h
  Source/santad/SNTDriverManager.m
Labels: enhancement

#284 Add CMake support, implement fuzzers
  CMakeLists.txt
  CocoaPods/CMakeLists.txt
  Conf/config.plist
  Conf/install.sh
  Conf/uninstall.sh
  Fuzzing/CMakeLists.txt
  Fuzzing/libFuzzer/.gitignore
  Fuzzing/libFuzzer/build.sh
  Fuzzing/santacache/.gitignore
  Fuzzing/santacache/CMakeLists.txt
  Fuzzing/santacache/santacache_fuzzer_seed_corpus/example01
  Fuzzing/santacache/src/main.cpp
  Fuzzing/santactl/CMakeLists.txt
  Fuzzing/santactl/santactl_fuzzer_seed_corpus/example01
  Fuzzing/santactl/src/main.mm
  Fuzzing/santad/CMakeLists.txt
  Fuzzing/santad/santad_checkCacheForVnodeID_fuzzer_seed_corpus/example01
  Fuzzing/santad/santad_databaseRemoveEventsWithIDs_fuzzer_seed_corpus/example01
  Fuzzing/santad/santad_databaseRuleAddRules_fuzzer_seed_corpus/example01
  Fuzzing/santad/src/checkCacheForVnodeID.mm
  Fuzzing/santad/src/databaseRemoveEventsWithIDs.mm
  Fuzzing/santad/src/databaseRuleAddRules.mm
  README.md
  Source/SantaGUI/CMakeLists.txt
  Source/SantaGUI/Resources/SantaGUI-Info.plist
  Source/santa-driver/CMakeLists.txt
  Source/santa-driver/Resources/santa-driver-Info.plist
  Source/santa-driver/main.c
  Source/santabs/CMakeLists.txt
  Source/santabs/Resources/santabs-Info.plist
  Source/santactl/CMakeLists.txt
  Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.h
  Source/santactl/Resources/santactl-Info.plist
  Source/santad/CMakeLists.txt
  Source/santad/Resources/santad-Info.plist
  Tests/CMakeLists.txt
  Tests/KernelTests/CMakeLists.txt
  Tests/santa-driver/CMakeLists.txt
  Tests/santa-driver/main.mm
Labels: cla:yes, enhancement
