Repository google/santa, pull requests merged in 2020-10, with the labels that each got.

#494 Make it possible to remotely set the FullSyncInterval
  Source/santactl/Commands/sync/SNTCommandSyncConstants.h
  Source/santactl/Commands/sync/SNTCommandSyncConstants.m
  Source/santactl/Commands/sync/SNTCommandSyncManager.m
  Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
  Source/santactl/Commands/sync/SNTCommandSyncState.h
  docs/deployment/configuration.md
Labels: cla:yes, enhancement

#500 Project: Update dependency versions
  WORKSPACE
Labels: bug

#502 santa-driver: Fix some new Xcode 12 warnings
  Source/santa_driver/BUILD
  Source/santa_driver/SantaDecisionManager.cc
Labels: cleanup

#503 Project: move travis to xcode12
  .travis.yml
Labels: enhancement

#504 Project: fix some lint
  Source/common/BUILD
  Source/common/SNTBlockMessage.m
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/santa/BUILD
  Source/santa_driver/BUILD
  Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
  Source/santad/EventProviders/SNTEndpointSecurityManager.mm
Labels: enhancement

#505 Kernel: fix some header imports
  Source/common/BUILD
  Source/common/SNTKernelCommon.h
Labels: cleanup
