Repository google/santa, pull requests merged in 2021-10, with the labels that each got.

#616 Detect existence of a provisionprofile and use that instead in build_and_sign.sh
  Testing/build_and_sign.sh
  Testing/init_dev_certs.sh
  Testing/start_env.sh
Labels: cla: yes

#617 Add provisioningprofile for santactl so that it's properly signed
  Source/santactl/BUILD
  WORKSPACE
Labels: cla: yes

#618 Add regular execution integration tests
  Testing/integration/BUILD
  Testing/integration/SNTExecTest.m
  Testing/integration_tests.sh
  Testing/start_env.sh
Labels: cla: yes

#619 Run buildifier and include license for new BUILD file
  Testing/integration/BUILD
Labels: cla: yes

#620 Add linter step with clang-format and buildifier.
  .github/workflows/ci.yml
  BUILD
  Source/common/BUILD
  Source/common/SNTXPCMetricServiceInterface.m
  Source/santa/BUILD
  Source/santa_driver/BUILD
  Source/santactl/BUILD
  Source/santad/BUILD
  Testing/integration/BUILD
  Testing/lint.sh
  WORKSPACE
Labels: cla: yes

#622 README: sync servers; remove Upvote, sort the rest alphabetically.
  README.md
Labels: cla: yes

#623 Tests: ensure SNTPrefixTree test finishes executing at appropriate time
  Source/common/SNTPrefixTreeTest.mm
Labels: cla: yes

#624 Initial commit of an HTTP writer for SNTMetricSets
  Source/santametricservice/BUILD
  Source/santametricservice/Formats/SNTMetricRawJSONFormat.m
  Source/santametricservice/SNTMetricService.m
  Source/santametricservice/SNTMetricServiceTest.m
  Source/santametricservice/Writers/BUILD
  Source/santametricservice/Writers/SNTMetricHTTPWriter.h
  Source/santametricservice/Writers/SNTMetricHTTPWriter.m
  Source/santametricservice/Writers/SNTMetricHTTPWriterTest.m
Labels: cla: yes, metrics

#625 santactl/sync: Fix tests for santactl/sync
  Source/santactl/BUILD
  Source/santactl/Commands/sync/SNTCommandSyncTest.m
Labels: cla: yes

#626 Project: Fix issues link in README
  README.md
Labels: cla: yes

#628 Add a workflow for checking links in Markdown files
  .github/workflows/check-markdown-links.yml
Labels: cleanup, cla: yes
