Repository google/santa, pull requests merged in 2021-12, with the labels that each got.

#687 Add a metrics command to santactl
  BUILD
  Source/common/BUILD
  Source/common/SNTMetricSet.h
  Source/common/SNTMetricSet.m
  Source/common/SNTMetricSetTest.m
  Source/common/SNTXPCUnprivilegedControlInterface.h
  Source/santactl/BUILD
  Source/santactl/Commands/SNTCommandMetrics.h
  Source/santactl/Commands/SNTCommandMetrics.m
  Source/santactl/Commands/SNTCommandMetricsTest.m
  Source/santactl/Commands/testdata/metrics-prettyprint.json
  Source/santactl/Commands/testdata/metrics-prettyprint.txt
  Source/santad/SNTDaemonControlController.m
Labels: cla: yes, metrics

#692 Ignore VSCode directories
  .gitignore
Labels: cleanup

#693 Fix: SNTMetricSet reregistering metrics returns wrong metric
  Source/common/SNTMetricSet.m
  Source/common/SNTMetricSetTest.m
Labels: bug, metrics

#694 Add a simple event counter to SNTExecutionController
  Source/santad/BUILD
  Source/santad/SNTExecutionController.h
  Source/santad/SNTExecutionController.m
  Source/santad/SNTExecutionControllerTest.m
Labels: metrics

#696 santasyncservice: move sync code to the santasyncservice dir
  BUILD
  Fuzzing/santactl/src/main.mm
  Source/santactl/BUILD
  Source/santactl/Commands/SNTCommandSync.m
  Source/santasyncservice/BUILD
  Source/santasyncservice/NSData+Zlib.h
  Source/santasyncservice/NSData+Zlib.m
  Source/santasyncservice/SNTSyncConstants.h
  Source/santasyncservice/SNTSyncConstants.m
  Source/santasyncservice/SNTSyncEventUpload.h
  Source/santasyncservice/SNTSyncEventUpload.m
  Source/santasyncservice/SNTSyncFCM.h
  Source/santasyncservice/SNTSyncFCM.m
  Source/santasyncservice/SNTSyncManager.h
  Source/santasyncservice/SNTSyncManager.m
  Source/santasyncservice/SNTSyncPostflight.h
  Source/santasyncservice/SNTSyncPostflight.m
  Source/santasyncservice/SNTSyncPreflight.h
  Source/santasyncservice/SNTSyncPreflight.m
  Source/santasyncservice/SNTSyncRuleDownload.h
  Source/santasyncservice/SNTSyncRuleDownload.m
  Source/santasyncservice/SNTSyncStage.h
  Source/santasyncservice/SNTSyncStage.m
  Source/santasyncservice/SNTSyncState.h
  Source/santasyncservice/SNTSyncState.m
  Source/santasyncservice/SNTSyncTest.m
  Source/santasyncservice/testdata/sync_eventupload_input_basic.plist
  Source/santasyncservice/testdata/sync_eventupload_input_quarantine.plist
  Source/santasyncservice/testdata/sync_preflight_basic.json
  Source/santasyncservice/testdata/sync_preflight_lockdown.json
  Source/santasyncservice/testdata/sync_ruledownload_batch1.json
  Source/santasyncservice/testdata/sync_ruledownload_batch2.json
Labels: enhancement, cleanup

#697 Fix: santactl metrics command behavior
  Source/santad/SNTDaemonControlController.m
Labels: metrics

#685 USB mass storage blocking and remounting
  BUILD
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/common/SNTXPCControlInterface.h
  Source/santad/BUILD
  Source/santad/EventProviders/EndpointSecurityTestUtil.h
  Source/santad/EventProviders/EndpointSecurityTestUtil.mm
  Source/santad/EventProviders/SNTDeviceManager.h
  Source/santad/EventProviders/SNTDeviceManager.mm
  Source/santad/EventProviders/SNTDeviceManagerTest.mm
  Source/santad/EventProviders/SNTEndpointSecurityManager.mm
  Source/santad/EventProviders/SNTEndpointSecurityManagerTest.mm
  Source/santad/SNTApplication.m
  Source/santad/SNTApplicationBenchmark.m
  Source/santad/SNTApplicationTest.m
  Source/santad/SNTDaemonControlController.m
  Source/santasyncservice/SNTSyncConstants.h
  Source/santasyncservice/SNTSyncConstants.m
  Source/santasyncservice/SNTSyncPostflight.m
  Source/santasyncservice/SNTSyncPreflight.m
  Source/santasyncservice/SNTSyncState.h
  Testing/com.google.santa.mobileconfig
  docs/deployment/configuration.md
Labels: enhancement, cla: yes
