Repository google/santa, pull requests merged in 2021-01, with the labels that each got.

#523 santactl/fileinfo: Fix fileinfo tests on BigSur + multiarch plists
  Source/common/BUILD
  Source/common/SNTFileInfo.m
  Source/common/SNTFileInfoTest.m
  Source/common/testdata/32bitplist
Labels: cla: yes

#525 The configuration key "enabled_transitive_rules" should be "enable_transitive_rules"
  docs/deployment/configuration.md
Labels: cla: yes

#526 santactl/sync: retry individual requests during a sync
  Source/santactl/Commands/sync/SNTCommandSyncManager.m
  Source/santactl/Commands/sync/SNTCommandSyncStage.m
Labels: cla: yes, enhancement

#528 Docs: Fix some broken links in the index
  docs/development/contributing.md
  docs/index.md
Labels: bug, cla: yes

#529 add .mobilecofig profile to enable Notifications settings for Santa
  docs/deployment/notificationsettings.santa.example.mobileconfig
Labels: cla: yes

#530 Docs: the docs build can't use symlinks ref. out of the docs dir
  CONTRIBUTING.md
  docs/development/contributing.md
Labels: cla: yes

#531 Docs: fix syncing-overview link in santactl doc
  docs/details/santactl.md
Labels: cla: yes

#533 santad: Fix caching of deny decisions
  Source/santad/EventProviders/SNTCachingEndpointSecurityManager.mm
  Source/santad/EventProviders/SNTEndpointSecurityManager.mm
  version.bzl
Labels: cla: yes

#534 Project: run buildifier on BUILD files
  Source/santa_driver/BUILD
Labels: cla: yes
