Repository google/santa, pull requests merged in 2021-09, with the labels that each got.

#592 Make CI build and test steps conditional
  .github/workflows/ci.yml
Labels: cleanup, cla: yes

#593 Rewrote ci.yml workflow to parallelize steps
  .github/workflows/ci.yml
Labels: cleanup, cla: yes

#596 Add tulsi project
  .gitignore
  docs/development/building.md
  santa.tulsiproj/Configs/Santa.tulsigen
  santa.tulsiproj/project.tulsiconf
Labels: cla: yes

#597 Add Rudolph to list of sync servers
  README.md
Labels: cla: yes

#598 Add entitlements to the santad and Santa build rules
  Source/santa/BUILD
  Source/santad/BUILD
  Source/santad/com.google.santa.daemon.systemextension.entitlements
Labels: cla: yes

#599 Explicitly include the TeamIdentifierPrefix to santad's entitlement
  Source/santad/com.google.santa.daemon.systemextension.entitlements
Labels: cla: yes

#602 Include an integration test setup and fixture with moroz
  .gitignore
  Source/santa/BUILD
  Source/santactl/BUILD
  Source/santad/BUILD
  Source/santad/com.google.santa.daemon.systemextension.entitlements
  Testing/build_and_sign.sh
  Testing/com.google.santa.mobileconfig
  Testing/global.toml
  Testing/init_dev_certs.sh
  Testing/openssl.cnf
  Testing/reset.sh
  Testing/start_env.sh
Labels: cla: yes

#603 Added an XPC interface for the Metric Service
  Source/common/BUILD
  Source/common/SNTXPCMetricServiceInterface.h
  Source/common/SNTXPCMetricServiceInterface.m
Labels: cla: yes, metrics

#604 Add initial configuration options for barebones metric service
  Source/common/SNTCommonEnums.h
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  docs/deployment/configuration.md
Labels: cla: yes, metrics

#605 Initial commit of santametricservice.
  Source/santametricservice/BUILD
  Source/santametricservice/Formats/BUILD
  Source/santametricservice/Formats/SNTMetricFormat.h
  Source/santametricservice/Formats/SNTMetricRawJSONFormat.h
  Source/santametricservice/Formats/SNTMetricRawJSONFormat.m
  Source/santametricservice/Formats/SNTMetricRawJSONFormatTest.m
  Source/santametricservice/Formats/testdata/json/test.json
  Source/santametricservice/Info.plist
  Source/santametricservice/SNTMetricService.h
  Source/santametricservice/SNTMetricService.m
  Source/santametricservice/SNTMetricServiceTest.m
  Source/santametricservice/Writers/BUILD
  Source/santametricservice/Writers/SNTMetricFileWriter.h
  Source/santametricservice/Writers/SNTMetricFileWriter.m
  Source/santametricservice/Writers/SNTMetricFileWriterTest.m
  Source/santametricservice/Writers/SNTMetricWriter.h
  Source/santametricservice/main.m
Labels: cla: yes, metrics

#606 Create block builder for ES Messages and clean up tests
  Source/santad/EventProviders/EndpointSecurityTestUtil.h
  Source/santad/EventProviders/EndpointSecurityTestUtil.mm
  Source/santad/EventProviders/SNTEndpointSecurityManagerTest.mm
  Source/santad/SNTApplicationTest.m
Labels: cla: yes

#607 Refactored metric service tests to use a common helper
  Source/santametricservice/BUILD
  Source/santametricservice/Formats/BUILD
  Source/santametricservice/Formats/SNTMetricFormatTestHelper.h
  Source/santametricservice/Formats/SNTMetricFormatTestHelper.m
  Source/santametricservice/Formats/SNTMetricRawJSONFormatTest.m
  Source/santametricservice/SNTMetricServiceTest.m
Labels: cleanup, cla: yes, metrics

#608 Metric: Fix formatting of SNTMetricFormatTestHelper
  Source/santametricservice/Formats/SNTMetricFormatTestHelper.m
Labels: cla: yes

#609 santactl/sync: Catch rare crash in FCM parsing
  Source/santactl/Commands/sync/SNTCommandSyncManager.m
Labels: cla: yes

#611 Project: fix some BUILD file lint
  Source/common/BUILD
  Source/santa/BUILD
  Source/santabundleservice/BUILD
  Source/santactl/BUILD
  Source/santad/BUILD
  Source/santad/testdata/BUILD
  Source/santametricservice/BUILD
  Source/santametricservice/Formats/BUILD
  Source/santametricservice/Writers/BUILD
  Source/santasyncservice/BUILD
Labels: cla: yes

#612 Project: fix exporting of SantaCache header
  Source/common/BUILD
Labels: cla: yes

#614 Deflake SNTApplicationTest by tracking subscriptions to specific event types
  Source/santad/EventProviders/EndpointSecurityTestUtil.h
  Source/santad/EventProviders/EndpointSecurityTestUtil.mm
  Source/santad/EventProviders/SNTEndpointSecurityManagerTest.mm
  Source/santad/SNTApplicationTest.m
Labels: cla: yes

#615 Remove use of entitlements field for the santad build rule
  Source/santad/BUILD
  Source/santad/com.google.santa.daemon.systemextension.entitlements
  Testing/build_and_sign.sh
  Testing/init_dev_certs.sh
  Testing/reset.sh
Labels: cla: yes
