Repository google/santa, pull requests merged in 2021-11, with the labels that each got.

#662 Add AboutText option for the Santa.app
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/santa/Resources/AboutWindow.xib
  Source/santa/SNTAboutWindowController.h
  Source/santa/SNTAboutWindowController.m
  docs/deployment/configuration.md
Labels: cla: yes

#665 Fix Flaky Execution Controller Tests
  Source/santad/SNTExecutionControllerTest.m
Labels: cleanup, cla: yes

#666 Tests: Fix some flaky tests
  Source/santad/SNTExecutionControllerTest.m
  Source/santametricservice/Formats/SNTMetricRawJSONFormat.m
  Source/santametricservice/Writers/SNTMetricHTTPWriterTest.m
Labels: cla: yes

#667 Tests: Stop using NSInvocation with OCMock's .andDo()
  Source/santametricservice/SNTMetricServiceTest.m
  Source/santametricservice/Writers/SNTMetricHTTPWriterTest.m
Labels: cla: yes

#669 Tests: Fix MetricServiceTest compatible with public OCMock
  Source/santametricservice/SNTMetricServiceTest.m
  Source/santametricservice/Writers/SNTMetricHTTPWriterTest.m
Labels: cleanup, cla: yes

#670 Change SNTEventLog to be a singleton emit a singleton Logger object
  Source/santad/BUILD
  Source/santad/Logs/SNTEventLog.h
  Source/santad/Logs/SNTEventLog.m
  Source/santad/SNTApplication.m
  Source/santad/SNTCompilerController.h
  Source/santad/SNTCompilerController.m
  Source/santad/SNTDaemonControlController.h
  Source/santad/SNTDaemonControlController.m
  Source/santad/SNTExecutionController.h
  Source/santad/SNTExecutionController.m
  Source/santad/SNTExecutionControllerTest.m
Labels: cla: yes

#673 Tests: Update SNTMetricHTTPWriterTest
  Source/santametricservice/Writers/SNTMetricHTTPWriterTest.m
Labels: cla: yes

#674 Do not store Allow TeamID events in the database
  Source/santad/SNTExecutionController.m
Labels: cla: yes

#675 Update help text for --teamid in santactl
  Source/santactl/Commands/SNTCommandRule.m
Labels: cla: yes

#676 Fixed up typo related to hostname vs. host_name
  Source/santad/SNTApplicationCoreMetrics.m
  Source/santad/SNTApplicationCoreMetricsTest.m
Labels: cleanup, cla: yes, metrics

#678 Update santactl fileinfo, sync, and status to show teamID info
  Source/common/SNTXPCUnprivilegedControlInterface.h
  Source/santactl/Commands/SNTCommandFileInfo.m
  Source/santactl/Commands/SNTCommandRule.m
  Source/santactl/Commands/SNTCommandStatus.m
  Source/santactl/Commands/sync/SNTCommandSyncConstants.h
  Source/santactl/Commands/sync/SNTCommandSyncConstants.m
  Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
  Source/santactl/Commands/sync/SNTCommandSyncTest.m
  Source/santad/DataLayer/SNTRuleTable.h
  Source/santad/DataLayer/SNTRuleTable.m
  Source/santad/DataLayer/SNTRuleTableTest.m
  Source/santad/SNTDaemonControlController.m
  Source/santad/SNTPolicyProcessor.h
  Source/santad/SNTPolicyProcessor.m
  docs/details/rules.md
Labels: cla: yes

#679 Add santametricservice information to $ santactl status
  Source/santactl/Commands/SNTCommandStatus.m
Labels: cla: yes, metrics

#683 Add a configuration option for users to add their own root labels
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/common/SNTMetricSet.h
  Source/common/SNTMetricSet.m
  Source/common/SNTMetricSetTest.m
  Source/santad/SNTApplicationCoreMetrics.m
  Source/santad/SNTApplicationCoreMetricsTest.m
  docs/deployment/configuration.md
Labels: cla: yes, metrics

#684 EnableSysxCache docs, etc
  docs/deployment/configuration.md
  docs/deployment/troubleshooting.md
  docs/details/logs.md
  docs/index.md
Labels: cla: yes
