Repository google/santa, pull requests merged in 2022-05, with the labels that each got.

#797 GUI: Add %bundle_or_file_sha% translation key
  Source/common/SNTBlockMessage.m
  docs/deployment/configuration.md
Labels: enhancement

#796 Sync: Add option to enable event upload despite clean sync.
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/santasyncservice/SNTSyncEventUpload.m
  docs/deployment/configuration.md
Labels: enhancement

#794 Created a profiles package so provisioning profiles only need to be in one place.
  Source/santa/BUILD
  Source/santabundleservice/BUILD
  Source/santactl/BUILD
  Source/santad/BUILD
  Source/santametricservice/BUILD
  Source/santasyncservice/BUILD
  profiles/BUILD
Labels: cleanup

#798 Added macos-12 to the build matrix
  .github/workflows/ci.yml
Labels: cleanup

#801 Fix ES Mock Client Subscription issues
  Source/santad/EventProviders/EndpointSecurityTestUtil.h
  Source/santad/EventProviders/EndpointSecurityTestUtil.mm
Labels: cleanup

#803 santad: remove start and stop options from the sync service queue
  Source/santad/SNTSyncdQueue.h
  Source/santad/SNTSyncdQueue.m
Labels: sync service

#802 GUI: Update keys for EventDetailURL.
  Source/common/SNTBlockMessage.m
  docs/deployment/configuration.md
Labels: enhancement

#805 GUI: Fix message queuing
  Source/santa/SNTMessageWindowController.m
  Source/santa/SNTNotificationManager.m
Labels: bug

#810 syncservice: Fix SNTSyncTest
  Source/santasyncservice/SNTSyncTest.m
Labels: bug

#811 Project: Enable layering check, fix all dependency violations
  Source/common/BUILD
  Source/santa/BUILD
  Source/santabundleservice/BUILD
  Source/santactl/BUILD
  Source/santad/BUILD
  Source/santametricservice/BUILD
  Source/santametricservice/Formats/BUILD
  Source/santametricservice/Writers/BUILD
  Source/santasyncservice/BUILD
  profiles/BUILD
Labels: enhancement

#816 Remove unused testing scripts
  Testing/build_and_sign.sh
  Testing/init_dev_certs.sh
  Testing/integration_tests.sh
  Testing/openssl.cnf
  Testing/reset.sh
  Testing/start_env.sh
Labels: cleanup
