Repository google/santa, pull requests merged in 2022-07, with the labels that each got.

#834 Docs: Add gemfile for running jekyll locally.
  docs/.gitignore
  docs/Gemfile
Labels: docs

#841 Docs: Updated home page with README files & nav changes
  docs/Gemfile
  docs/binaries/block.png
  docs/binaries/index.md
  docs/binaries/push.png
  docs/binaries/santa-gui.md
  docs/binaries/santabs.md
  docs/binaries/santactl.md
  docs/binaries/santad.md
  docs/concepts/events.md
  docs/concepts/index.md
  docs/concepts/ipc.md
  docs/concepts/logs.md
  docs/concepts/mode.md
  docs/concepts/rules.md
  docs/concepts/santa_ipc.png
  docs/concepts/scopes.md
  docs/deployment/troubleshooting.md
  docs/development/index.md
  docs/index.md
  docs/introduction/binary-authorization-overview.md
  docs/known-limitations.md
Labels: cla: yes, docs

#847 santad: Improve caching of static rules
  Source/common/SNTConfigurator.m
  Source/common/SNTRule.m
Labels: bug

#851 santasyncservice: Keep XSRF token in memory, don't send to daemon
  Source/common/SNTXPCControlInterface.h
  Source/common/SNTXPCUnprivilegedControlInterface.h
  Source/santad/SNTDaemonControlController.m
  Source/santasyncservice/SNTSyncManager.m
  Source/santasyncservice/SNTSyncStage.m
Labels: sync service

#849 santad: Fix re-establishment of syncservice connection
  Source/santad/SNTApplication.m
Labels: bug

#852 santad: Add DisableUnknownEventUpload option.
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/common/SNTMetricSet.h
  Source/common/SNTMetricSet.m
  Source/common/SNTSyncConstants.h
  Source/common/SNTSyncConstants.m
  Source/common/SNTXPCControlInterface.h
  Source/santad/SNTDaemonControlController.m
  Source/santad/SNTExecutionController.m
  Source/santad/SNTExecutionControllerTest.m
  Source/santasyncservice/SNTSyncPreflight.m
  docs/deployment/configuration.md
Labels: enhancement

#850 santad: Log team ID in execution logs, where available
  Source/common/santa.proto
  Source/santad/Logs/SNTProtobufEventLog.m
  Source/santad/Logs/SNTSyslogEventLog.m
Labels: enhancement

#853 Ensure KVO works for USB config options
  Source/common/SNTConfigurator.m
Labels: USB Mass Storage Blocking

#857 Tests: Fix un-needed expectation in SNTExecutionControllerTest.allEve…
  Source/santad/SNTExecutionControllerTest.m
Labels: cleanup

#864 syncservice: Add tests for NSData+Zlib and Postflight
  Source/santasyncservice/BUILD
  Source/santasyncservice/NSDataZlibTest.m
  Source/santasyncservice/SNTSyncTest.m
  Source/santasyncservice/testdata/sync_preflight_basic.gz
  Source/santasyncservice/testdata/sync_preflight_basic.z
Labels: enhancement, sync service

#860 Sync Protocol Docs
  docs/development/sync-protocol.md
Labels: docs
