Repository google/santa, pull requests merged in 2022-03, with the labels that each got.

#741 Fix: Issue with SNTMetricHTTPWriter Timeouts
  Source/santametricservice/Writers/SNTMetricHTTPWriter.m
Labels: bug, metrics

#743 Fix: uninstall.sh to remove the metric & bundle services.
  Conf/uninstall.sh
Labels: packaging

#749 Remove the Santa kernel extension.
  .github/workflows/ci.yml
  BUILD
  Conf/Package/postinstall
  Conf/install.sh
  Source/common/BUILD
  Source/common/SNTCachedDecision.h
  Source/common/SNTCommon.h
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/common/SNTXPCControlInterface.m
  Source/common/SNTXPCUnprivilegedControlInterface.h
  Source/common/SantaCache.h
  Source/santa/main.m
  Source/santa_driver/BUILD
  Source/santa_driver/Info.plist
  Source/santa_driver/SantaDecisionManager.cc
  Source/santa_driver/SantaDecisionManager.h
  Source/santa_driver/SantaDriver.cc
  Source/santa_driver/SantaDriver.h
  Source/santa_driver/SantaDriverClient.cc
  Source/santa_driver/SantaDriverClient.h
  Source/santa_driver/kernel_tests.mm
  Source/santa_driver/main.cc
  Source/santactl/BUILD
  Source/santactl/Commands/SNTCommandStatus.m
  Source/santactl/Commands/SNTCommandVersion.m
  Source/santad/BUILD
  Source/santad/EventProviders/SNTDriverManager.h
  Source/santad/EventProviders/SNTDriverManager.m
  Source/santad/EventProviders/SNTEndpointSecurityManager.h
  Source/santad/EventProviders/SNTEventProvider.h
  Source/santad/Logs/SNTEventLog.h
  Source/santad/SNTApplication.m
  Source/santad/SNTApplicationBenchmark.m
  Source/santad/SNTApplicationTest.m
  Source/santad/SNTCompilerController.h
  Source/santad/SNTCompilerController.m
  Source/santad/SNTDaemonControlController.h
  Source/santad/SNTExecutionController.h
  Source/santad/SNTExecutionControllerTest.m
  Source/santad/SNTPolicyProcessor.h
  Source/santad/main.m
  Source/santametricservice/BUILD
  Source/santametricservice/Formats/BUILD
  Source/santametricservice/Writers/BUILD
  Source/santasyncservice/BUILD
  Source/santasyncservice/SNTSyncPreflight.m
Labels: cleanup

#750 Made santad an early boot client to prevent racing other processes
  Source/santad/Info.plist
Labels: cleanup

#752 Remove code guarded by #ifdef kernel macros
  Source/common/BUILD
  Source/common/SNTCommon.h
  Source/common/SNTCommonEnums.h
  Source/common/SNTLogging.h
  Source/common/SNTPrefixTree.cc
  Source/common/SNTPrefixTree.h
  Source/common/SantaCache.h
  Source/santactl/BUILD
Labels: cleanup, kext

#762 Docs: Remove references to kexts and santa-driver from parts of the docs
  README.md
  docs/details/ipc.md
  docs/details/logs.md
  docs/details/santa-driver.md
  docs/details/santabs.md
  docs/details/santactl.md
  docs/index.md
Labels: cleanup, docs

#765 santad: Split ES cache into root/non-root varieties
  Source/santactl/Commands/SNTCommandStatus.m
  Source/santad/EventProviders/SNTCachingEndpointSecurityManager.mm
Labels: enhancement

#766 Project: Make versioning dynamic through bazel's --embed-label.
  BUILD
  Source/santa/BUILD
  Source/santabundleservice/BUILD
  Source/santactl/BUILD
  Source/santad/BUILD
  Source/santasyncservice/BUILD
  Testing/build_and_sign.sh
  helper.bzl
  version.bzl
Labels: enhancement

#768 Exclude bazel-out from test coverage generation
  generate_cov.sh
Labels: cleanup

#767 Project: Fix fallback version
  BUILD
Labels: bug, cleanup

#770 Project: Fix coverage collection
  .github/workflows/ci.yml
  generate_cov.sh
Labels: cleanup

#773 Update logo image of Santa
  README.md
Labels: cleanup, docs

#774 Fix dead link
  docs/introduction/binary-authorization-overview.md
Labels: cleanup, docs
