Repository google/santa, pull requests merged in 2022-02, with the labels that each got.

#726 Update version of bazel rules_apple to fix broken 12.3 builds
  WORKSPACE
Labels: bug

#730 santad: Fix fail open tests in SNTExecutionControllerTest
  Source/santad/SNTExecutionControllerTest.m
Labels: cleanup

#733 Project: Add arm64 to hostArchitectures for productbuild
  Conf/Package/Distribution.xml
Labels: enhancement

#736 Project: Add build version to CFBundleVersion
  BUILD
  Source/santactl/Commands/SNTCommandVersion.m
  Source/santad/main.m
Labels: enhancement
