Repository google/santa, pull requests merged in 2022-06, with the labels that each got.

#822 santad: Copy/retain ES message for use in deadline handler.
  Source/santad/EventProviders/SNTDeviceManager.mm
  Source/santad/EventProviders/SNTEndpointSecurityManager.mm
Labels: bug

#818 Added handling for Remount events to USB mass storage blocking
  Source/santad/BUILD
  Source/santad/EventProviders/SNTDeviceManager.mm
  Source/santad/EventProviders/SNTDeviceManagerTest.mm
Labels: USB Mass Storage Blocking

#829 Readme: http -> https link
  README.md
Labels: cla: yes, docs

#827 Add team ID to synced events
  Source/common/SNTStoredEvent.h
  Source/common/SNTStoredEvent.m
  Source/santad/SNTExecutionController.m
  Source/santasyncservice/SNTSyncConstants.h
  Source/santasyncservice/SNTSyncConstants.m
  Source/santasyncservice/SNTSyncEventUpload.m
  Source/santasyncservice/SNTSyncTest.m
  Source/santasyncservice/testdata/sync_eventupload_input_basic.plist
  docs/details/events.md
Labels: enhancement, sync service
