Repository google/santa, pull requests merged in 2022-01, with the labels that each got.

#706 Project: Explicitly set calendar on ISO8601 dates
  Source/santad/Logs/SNTEventLog.m
  Source/santametricservice/Formats/SNTMetricFormatTestHelper.m
  Source/santametricservice/Formats/SNTMetricRawJSONFormat.m
  Source/santametricservice/SNTMetricServiceTest.m
Labels: cleanup

#707 santad: Don't use proc_pidpath when using ES
  Source/santad/Logs/SNTSyslogEventLog.m
Labels: cleanup

#708 Sync: Allow configuring proxies
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/santasyncservice/SNTSyncManager.m
  docs/deployment/configuration.md
Labels: enhancement

#702 Create test suites for each component
  BUILD
  Source/common/BUILD
  Source/santad/BUILD
Labels: cleanup

#716 Conf: Delete and clean-up ASL conf, enable signaling on newsyslog.conf.
  BUILD
  Conf/com.google.santa.asl.conf
  Conf/com.google.santa.newsyslog.conf
  Conf/install.sh
Labels: enhancement, cleanup

#719 santactl/fileinfo: Switch certIndex to an NSNumber
  Source/santactl/Commands/SNTCommandFileInfo.m
  Source/santactl/Commands/SNTCommandFileInfoTest.m
Labels: cleanup

#720 Add DiskArbitrationTestUtil to shim out DiskArbitration for unit testing
  Source/santad/BUILD
  Source/santad/EventProviders/DiskArbitrationTestUtil.h
  Source/santad/EventProviders/DiskArbitrationTestUtil.mm
  Source/santad/EventProviders/SNTDeviceManager.h
  Source/santad/EventProviders/SNTDeviceManager.mm
  Source/santad/EventProviders/SNTDeviceManagerTest.mm
Labels: cleanup

#722 santad: Add fail-closed mode
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/santad/SNTExecutionController.h
  Source/santad/SNTExecutionController.m
  Source/santad/SNTExecutionControllerTest.m
  docs/deployment/configuration.md
Labels: enhancement
