Repository google/santa, pull requests merged in 2022-08, with the labels that each got.

#872 GUI: For App Store published apps, include team ID.
  Source/santa/SNTBinaryMessageWindowController.m
Labels: enhancement

#871 GUI: Add silent mode configuration option.
  Source/common/SNTConfigurator.h
  Source/common/SNTConfigurator.m
  Source/santa/SNTNotificationManager.m
  docs/deployment/com.google.santa.example.mobileconfig
  docs/deployment/configuration.md
Labels: enhancement

#870 Santa: Post distributed notification when showing block UI
  Source/santa/BUILD
  Source/santa/SNTNotificationManager.m
  Source/santa/SNTNotificationManagerTest.m
Labels: enhancement

#874 GUI: Improve signing chain key reporting in distributed notifications.
  BUILD
  Source/santa/BUILD
  Source/santa/SNTNotificationManager.m
Labels: enhancement

#877 Project: Rename Source/santa -> Source/gui
  BUILD
  Source/gui/BUILD
  Source/gui/Info.plist
  Source/gui/Resources/AboutWindow.xib
  Source/gui/Resources/DeviceMessageWindow.xib
  Source/gui/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
  Source/gui/Resources/Images.xcassets/AppIcon.appiconset/santa-hat-icon-128.png
  Source/gui/Resources/Images.xcassets/AppIcon.appiconset/santa-hat-icon-16.png
  Source/gui/Resources/Images.xcassets/AppIcon.appiconset/santa-hat-icon-256.png
  Source/gui/Resources/Images.xcassets/AppIcon.appiconset/santa-hat-icon-32.png
  Source/gui/Resources/Images.xcassets/AppIcon.appiconset/santa-hat-icon-64.png
  Source/gui/Resources/Images.xcassets/Contents.json
  Source/gui/Resources/MessageWindow.xib
  Source/gui/SNTAboutWindowController.h
  Source/gui/SNTAboutWindowController.m
  Source/gui/SNTAccessibleTextField.h
  Source/gui/SNTAccessibleTextField.m
  Source/gui/SNTAppDelegate.h
  Source/gui/SNTAppDelegate.m
  Source/gui/SNTBinaryMessageWindowController.h
  Source/gui/SNTBinaryMessageWindowController.m
  Source/gui/SNTDeviceMessageWindowController.h
  Source/gui/SNTDeviceMessageWindowController.m
  Source/gui/SNTMessageWindow.h
  Source/gui/SNTMessageWindow.m
  Source/gui/SNTMessageWindowController.h
  Source/gui/SNTMessageWindowController.m
  Source/gui/SNTNotificationManager.h
  Source/gui/SNTNotificationManager.m
  Source/gui/SNTNotificationManagerTest.m
  Source/gui/Santa.app-adhoc.entitlements
  Source/gui/main.m
Labels: cleanup

#879 Fix up endTimestamp to be Monarch compliant
  Source/santametricservice/Formats/BUILD
  Source/santametricservice/Formats/SNTMetricMonarchJSONFormat.m
  Source/santametricservice/Formats/SNTMetricMonarchJSONFormatTest.m
  Source/santametricservice/Formats/testdata/json/monarch.json
  Source/santametricservice/SNTMetricServiceTest.m
Labels: metrics
