Repository google/santa, pull requests merged in 2023-04, with the labels that each got.

#1066 GUI: Device event window, handle empty remount args
  Source/gui/SNTDeviceMessageWindowView.swift
Labels: bug

#1068 sync: Add more complete XSSI prefix to be stripped.
  Source/santasyncservice/SNTSyncStage.m
  Source/santasyncservice/SNTSyncTest.m
Labels: enhancement

#1075 README: Add more badges
  README.md
Labels: docs

#1081 sync: Permit XSRF header between sync stages/sessions
  Source/santasyncservice/SNTSyncManager.m
Labels: bug

#1080 Clarify that execution_time is a float64
  docs/development/sync-protocol.md
Labels: docs

#1082 Fix documentation for clean sync field in the preflight request.
  docs/development/sync-protocol.md
Labels: docs
